services:
  postgres:
    image: postgres:latest
    container_name: workout-planner_postgres_container
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=workout
      - POSTGRES_USER=workout
      - POSTGRES_DB=workout-planner

volumes:
    pgdata: